"use client";

import { useState, type FormEvent } from "react";
import type { ClinicalProtocolLibraryData } from "../lib/consultations";
import { HpsmButton, HpsmButtonLink } from "./hpsm-button";
import { HpsmDialog } from "./hpsm-dialog";

type Pending = { kind: "protocol"; id: string; label: string; status: "active" | "inactive" | "quarantined" } | { kind: "medication"; id: string; label: string; active: boolean };
export function ClinicalProtocolLibrary({ initialData }: { initialData: ClinicalProtocolLibraryData }) {
  const [data, setData] = useState(initialData); const [pending, setPending] = useState<Pending | null>(null); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [settings, setSettings] = useState(initialData.settings);
  async function mutate(body: Record<string, unknown>) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch("/api/consultations/protocols", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as ClinicalProtocolLibraryData & { error?: string }; if (!response.ok) throw new Error(payload.error || "Não foi possível atualizar a biblioteca."); setData(payload); setSettings(payload.settings); setPending(null); setReason(""); setNotice("Biblioteca atualizada com auditoria e versionamento."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível atualizar a biblioteca."); } finally { setBusy(false); } }
  function saveSettings(event: FormEvent) { event.preventDefault(); void mutate({ action: "settings", candidateToLearned: settings.candidate_to_learned_count, learnedToConsolidated: settings.learned_to_consolidated_count, mergeSimilarity: settings.merge_similarity_threshold, relatedSimilarity: settings.related_similarity_threshold, maxRelated: settings.max_related_protocols, reason: "Limiares revisados pela gestão clínica." }); }
  return <div className="protocol-library">
    <section className="consultation-hero"><div><span className="consultation-kicker">Memória clínica RP</span><h2>Biblioteca de Protocolos</h2><p>Padrões desidentificados aprendidos somente com consultas concluídas e decisões confirmadas. Não há nova chamada de IA nesta tela.</p></div><div className="consultation-hero-actions"><HpsmButtonLink href="/consultas">Voltar às consultas</HpsmButtonLink></div></section>
    {error ? <p className="form-error" role="alert">{error}</p> : null}{notice ? <p className="form-success" role="status">{notice}</p> : null}
    {data.can_moderate ? <form className="protocol-settings" onSubmit={saveSettings}><header><div><span className="consultation-kicker">Configuração auditada</span><h3>Limiares de aprendizado</h3></div><HpsmButton loading={busy} variant="primary" type="submit">Salvar limiares</HpsmButton></header><div><label>Candidato → aprendido<input min={2} max={100} type="number" value={settings.candidate_to_learned_count} onChange={(event) => setSettings({ ...settings, candidate_to_learned_count: Number(event.target.value) })} /></label><label>Aprendido → consolidado<input min={3} max={500} type="number" value={settings.learned_to_consolidated_count} onChange={(event) => setSettings({ ...settings, learned_to_consolidated_count: Number(event.target.value) })} /></label><label>Similaridade para mesclar<input min={0} max={1} step={.05} type="number" value={settings.merge_similarity_threshold} onChange={(event) => setSettings({ ...settings, merge_similarity_threshold: Number(event.target.value) })} /></label><label>Similaridade relacionada<input min={0} max={1} step={.05} type="number" value={settings.related_similarity_threshold} onChange={(event) => setSettings({ ...settings, related_similarity_threshold: Number(event.target.value) })} /></label><label>Máximo relacionado<input min={1} max={5} type="number" value={settings.max_related_protocols} onChange={(event) => setSettings({ ...settings, max_related_protocols: Number(event.target.value) })} /></label></div></form> : null}
    <section className="protocol-section"><header><div><span className="consultation-kicker">Protocolos clínicos</span><h3>{data.protocols.length} padrão(ões) observado(s)</h3></div></header>{data.protocols.length ? <div className="protocol-grid">{data.protocols.map((protocol) => <article key={protocol.id} data-status={protocol.moderation_status}><header><span>{protocol.state}</span><em>{protocol.moderation_status === "active" ? "Ativo" : protocol.moderation_status === "quarantined" ? "Em quarentena" : "Inativo"}</em></header><h4>{protocol.display_name}</h4><p>{protocol.primary_diagnosis}</p><dl><div><dt>Observações</dt><dd>{protocol.observed_count}</dd></div><div><dt>Sistema</dt><dd>{protocol.body_system}</dd></div><div><dt>Versão</dt><dd>{protocol.version}</dd></div></dl><small>{[...protocol.case_tags, ...protocol.vital_flags].slice(0, 8).join(" · ") || "Sem marcadores adicionais"}</small>{data.can_moderate ? <footer><HpsmButton disabled={busy || protocol.moderation_status === "active"} onClick={() => setPending({ kind: "protocol", id: protocol.id, label: protocol.display_name, status: "active" })}>Ativar</HpsmButton><HpsmButton disabled={busy || protocol.moderation_status === "quarantined"} onClick={() => setPending({ kind: "protocol", id: protocol.id, label: protocol.display_name, status: "quarantined" })}>Quarentena</HpsmButton><HpsmButton disabled={busy || protocol.moderation_status === "inactive"} variant="destructive" onClick={() => setPending({ kind: "protocol", id: protocol.id, label: protocol.display_name, status: "inactive" })}>Inativar</HpsmButton></footer> : null}</article>)}</div> : <div className="consultation-empty"><strong>A biblioteca ainda está vazia</strong><p>O primeiro protocolo surgirá após consultas concluídas com decisões clínicas confirmadas.</p></div>}</section>
    <section className="protocol-section"><header><div><span className="consultation-kicker">Catálogo canônico</span><h3>Anjos Pharma · {data.medications.length} medicamentos</h3></div><p>Catálogo RP sem estoque, saldo ou movimentação.</p></header><div className="medication-catalog-grid">{data.medications.map((medication) => <article key={medication.id} data-active={medication.active}><header><span>{medication.id}</span><em>{medication.active ? "Ativo" : "Inativo"}</em></header><h4>{medication.rp_name}</h4><p>{medication.reference_name} · {medication.category}</p><small>{medication.default_dose} · {medication.default_frequency} · {medication.default_duration} · {medication.default_route}</small>{medication.controlled || medication.antibiotic ? <b>{medication.controlled ? "Controlado" : "Antibiótico"} · justificativa obrigatória</b> : null}{data.can_moderate ? <footer><HpsmButton disabled={busy} variant={medication.active ? "destructive" : "primary"} onClick={() => setPending({ kind: "medication", id: medication.id, label: medication.rp_name, active: !medication.active })}>{medication.active ? "Inativar" : "Ativar"}</HpsmButton></footer> : null}</article>)}</div></section>
    {pending ? <HpsmDialog confirmLabel="Confirmar alteração" description={`${pending.label}: ${pending.kind === "protocol" ? pending.status : pending.active ? "ativar" : "inativar"}. A ação será versionada e auditada.`} loading={busy} onClose={() => { setPending(null); setReason(""); }} onConfirm={() => { if (reason.trim().length < 3) return; void mutate(pending.kind === "protocol" ? { action: "moderate", protocolId: pending.id, status: pending.status, reason } : { action: "medication", medicationId: pending.id, active: pending.active, reason }); }} title="Moderar biblioteca"><label className="dialog-field">Motivo<textarea autoFocus maxLength={500} minLength={3} required rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label></HpsmDialog> : null}
  </div>;
}
