-- HPSM Rollup 4: protocolos autoalimentados, catálogo Anjos Pharma e prescrições RP.
-- Não cria estoque, saldo, movimentação, entrada ou saída de medicamentos.

create table public.rp_medications (
  id text primary key,
  rp_name text not null unique,
  reference_name text not null,
  category text not null,
  active boolean not null default true,
  controlled boolean not null default false,
  antibiotic boolean not null default false,
  requires_justification boolean not null default false,
  allowed_body_systems text[] not null default '{}'::text[],
  allowed_case_tags text[] not null default '{}'::text[],
  disallowed_case_tags text[] not null default '{}'::text[],
  allergy_keywords text[] not null default '{}'::text[],
  default_dose text not null,
  default_frequency text not null,
  default_duration text not null,
  default_duration_days smallint not null,
  default_route text not null,
  default_instructions text not null,
  default_doses_per_day smallint not null,
  default_as_needed boolean not null default false,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rp_medications_id_check check (id ~ '^[A-Z0-9_]{3,40}$'),
  constraint rp_medications_text_check check (
    char_length(btrim(rp_name)) between 2 and 100
    and char_length(btrim(reference_name)) between 2 and 160
    and char_length(btrim(default_dose)) between 1 and 80
    and char_length(btrim(default_frequency)) between 1 and 120
    and char_length(btrim(default_duration)) between 1 and 80
    and char_length(btrim(default_route)) between 1 and 120
    and char_length(btrim(default_instructions)) between 1 and 500
  ),
  constraint rp_medications_duration_check check (default_duration_days between 1 and 365),
  constraint rp_medications_frequency_check check (default_doses_per_day between 1 and 24),
  constraint rp_medications_version_check check (version >= 1),
  constraint rp_medications_justification_check check (
    not (controlled or antibiotic) or requires_justification
  )
);

create table public.rp_medication_versions (
  id bigint generated by default as identity primary key,
  medication_id text not null references public.rp_medications(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null,
  changed_by uuid references public.profiles(user_id) on delete set null,
  change_reason text,
  created_at timestamptz not null default now(),
  constraint rp_medication_versions_unique unique (medication_id, version),
  constraint rp_medication_versions_snapshot_check check (jsonb_typeof(snapshot) = 'object')
);

create table public.clinical_protocol_settings (
  singleton boolean primary key default true,
  candidate_to_learned_count integer not null,
  learned_to_consolidated_count integer not null,
  merge_similarity_threshold numeric(4,3) not null,
  related_similarity_threshold numeric(4,3) not null,
  max_related_protocols integer not null,
  updated_at timestamptz not null default now(),
  constraint clinical_protocol_settings_singleton_check check (singleton),
  constraint clinical_protocol_settings_counts_check check (
    candidate_to_learned_count >= 2
    and learned_to_consolidated_count > candidate_to_learned_count
    and max_related_protocols between 1 and 5
  ),
  constraint clinical_protocol_settings_thresholds_check check (
    merge_similarity_threshold between 0 and 1
    and related_similarity_threshold between 0 and 1
  )
);

create table public.clinical_protocols (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null unique,
  display_name text not null,
  state text not null default 'CANDIDATE',
  moderation_status text not null default 'active',
  version integer not null default 0,
  observed_count integer not null default 0,
  body_system text not null,
  case_tags text[] not null default '{}'::text[],
  vital_flags text[] not null default '{}'::text[],
  primary_diagnosis text,
  first_observed_at timestamptz,
  last_observed_at timestamptz,
  moderated_at timestamptz,
  moderated_by uuid references public.profiles(user_id) on delete set null,
  moderation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clinical_protocols_state_check check (state in ('CANDIDATE', 'LEARNED', 'CONSOLIDATED')),
  constraint clinical_protocols_moderation_check check (moderation_status in ('active', 'inactive', 'quarantined')),
  constraint clinical_protocols_version_check check (version >= 0),
  constraint clinical_protocols_observed_check check (observed_count >= 0),
  constraint clinical_protocols_body_system_check check (body_system ~ '^[a-z0-9_]{2,60}$'),
  constraint clinical_protocols_display_name_check check (char_length(btrim(display_name)) between 3 and 160)
);

create table public.clinical_protocol_versions (
  id bigint generated by default as identity primary key,
  protocol_id uuid not null references public.clinical_protocols(id) on delete cascade,
  version integer not null,
  snapshot jsonb not null,
  change_type text not null,
  changed_by uuid references public.profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  constraint clinical_protocol_versions_unique unique (protocol_id, version),
  constraint clinical_protocol_versions_snapshot_check check (jsonb_typeof(snapshot) = 'object')
);

create table public.clinical_protocol_observations (
  id bigint generated by default as identity primary key,
  protocol_id uuid not null references public.clinical_protocols(id) on delete cascade,
  consultation_id bigint not null unique references public.clinical_consultations(id) on delete cascade,
  case_signature jsonb not null,
  decision_snapshot jsonb not null,
  observed_at timestamptz not null default now(),
  constraint clinical_protocol_observations_signature_check check (jsonb_typeof(case_signature) = 'object'),
  constraint clinical_protocol_observations_decision_check check (jsonb_typeof(decision_snapshot) = 'object')
);

create index clinical_protocols_matching_idx
  on public.clinical_protocols (moderation_status, state, body_system, observed_count desc);
create index clinical_protocol_observations_protocol_idx
  on public.clinical_protocol_observations (protocol_id, observed_at desc);

create table public.consultation_prescriptions (
  id uuid primary key default gen_random_uuid(),
  consultation_id bigint not null unique references public.clinical_consultations(id) on delete cascade,
  status text not null default 'draft',
  professional_id uuid not null references public.profiles(user_id) on delete restrict,
  patient_name_snapshot text,
  patient_passport_snapshot text,
  professional_name_snapshot text,
  crm_snapshot text,
  role_snapshot text,
  final_snapshot jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finalized_at timestamptz,
  constraint consultation_prescriptions_status_check check (status in ('draft', 'finalized')),
  constraint consultation_prescriptions_state_check check (
    (status = 'draft' and finalized_at is null and final_snapshot is null)
    or (status = 'finalized' and finalized_at is not null and jsonb_typeof(final_snapshot) = 'object')
  )
);

create table public.consultation_prescription_items (
  id uuid primary key default gen_random_uuid(),
  prescription_id uuid not null references public.consultation_prescriptions(id) on delete cascade,
  consultation_id bigint not null references public.clinical_consultations(id) on delete cascade,
  medication_id text not null references public.rp_medications(id) on delete restrict,
  source text not null,
  catalog_version integer not null,
  rp_name_snapshot text not null,
  reference_name_snapshot text not null,
  dose_snapshot text not null,
  frequency_snapshot text not null,
  duration_snapshot text not null,
  duration_days smallint not null,
  route_snapshot text not null,
  reason_snapshot text not null,
  instructions_snapshot text not null,
  justification_snapshot text,
  calculated_quantity_snapshot integer not null,
  final_quantity_snapshot integer not null,
  quantity_override_snapshot boolean not null default false,
  override_reason text,
  professional_id uuid not null references public.profiles(user_id) on delete restrict,
  professional_name_snapshot text,
  crm_snapshot text,
  role_snapshot text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consultation_prescription_items_unique unique (consultation_id, medication_id),
  constraint consultation_prescription_items_source_check check (source in ('ai', 'manual')),
  constraint consultation_prescription_items_duration_check check (duration_days between 1 and 365),
  constraint consultation_prescription_items_quantity_check check (
    calculated_quantity_snapshot between 1 and 1000
    and final_quantity_snapshot between 1 and 1000
    and quantity_override_snapshot = (calculated_quantity_snapshot <> final_quantity_snapshot)
  ),
  constraint consultation_prescription_items_override_check check (
    (not quantity_override_snapshot and override_reason is null)
    or (quantity_override_snapshot and char_length(btrim(coalesce(override_reason, ''))) between 3 and 500)
  )
);

create index consultation_prescription_items_prescription_idx
  on public.consultation_prescription_items (prescription_id, created_at, id);

create table public.consultation_medication_decisions (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null references public.clinical_consultations(id) on delete cascade,
  medication_id text not null references public.rp_medications(id) on delete restrict,
  source text not null,
  decision text not null,
  reason text,
  actor_user_id uuid not null references public.profiles(user_id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint consultation_medication_decisions_source_check check (source in ('ai', 'manual')),
  constraint consultation_medication_decisions_decision_check check (decision in ('accepted', 'rejected', 'removed'))
);

create index consultation_medication_decisions_consultation_idx
  on public.consultation_medication_decisions (consultation_id, medication_id, created_at desc);

alter table public.rp_medications enable row level security;
alter table public.rp_medications force row level security;
alter table public.rp_medication_versions enable row level security;
alter table public.rp_medication_versions force row level security;
alter table public.clinical_protocol_settings enable row level security;
alter table public.clinical_protocol_settings force row level security;
alter table public.clinical_protocols enable row level security;
alter table public.clinical_protocols force row level security;
alter table public.clinical_protocol_versions enable row level security;
alter table public.clinical_protocol_versions force row level security;
alter table public.clinical_protocol_observations enable row level security;
alter table public.clinical_protocol_observations force row level security;
alter table public.consultation_prescriptions enable row level security;
alter table public.consultation_prescriptions force row level security;
alter table public.consultation_prescription_items enable row level security;
alter table public.consultation_prescription_items force row level security;
alter table public.consultation_medication_decisions enable row level security;
alter table public.consultation_medication_decisions force row level security;

revoke all on public.rp_medications, public.rp_medication_versions,
  public.clinical_protocol_settings, public.clinical_protocols,
  public.clinical_protocol_versions, public.clinical_protocol_observations,
  public.consultation_prescriptions, public.consultation_prescription_items,
  public.consultation_medication_decisions
from public, anon, authenticated;

grant select, insert, update, delete on public.rp_medications, public.rp_medication_versions,
  public.clinical_protocol_settings, public.clinical_protocols,
  public.clinical_protocol_versions, public.clinical_protocol_observations,
  public.consultation_prescriptions, public.consultation_prescription_items,
  public.consultation_medication_decisions
to service_role;

grant usage, select on sequence public.rp_medication_versions_id_seq,
  public.clinical_protocol_versions_id_seq,
  public.clinical_protocol_observations_id_seq,
  public.consultation_medication_decisions_id_seq
to service_role;

insert into public.clinical_protocol_settings (
  singleton, candidate_to_learned_count, learned_to_consolidated_count,
  merge_similarity_threshold, related_similarity_threshold, max_related_protocols
) values (true, 3, 8, 0.550, 0.350, 3);

insert into public.rp_medications (
  id, rp_name, reference_name, category, controlled, antibiotic, requires_justification,
  allowed_body_systems, allowed_case_tags, disallowed_case_tags, allergy_keywords,
  default_dose, default_frequency, default_duration, default_duration_days,
  default_route, default_instructions, default_doses_per_day, default_as_needed
) values
  ('ANALGEX', 'Analgex', 'Dipirona', 'Analgésico', false, false, false, '{}', '{}', '{}', array['analgex','dipirona'], '500 mg', 'a cada 6 horas, se necessário', '3 dias', 3, 'Oral', 'Usar se necessário, respeitando a frequência máxima RP.', 4, true),
  ('PARADOR', 'Parador', 'Paracetamol', 'Analgésico', false, false, false, '{}', '{}', '{}', array['parador','paracetamol'], '500 mg', 'a cada 6 horas, se necessário', '3 dias', 3, 'Oral', 'Usar se necessário, respeitando a frequência máxima RP.', 4, true),
  ('CEFALIV', 'Cefaliv', 'Neosaldina', 'Analgésico', false, false, false, '{}', array['cefaleia'], '{}', array['cefaliv','neosaldina'], '1 dose', 'a cada 6 horas, se necessário', '2 dias', 2, 'Oral', 'Usar se necessário, respeitando a frequência máxima RP.', 4, true),
  ('MUSCULIV', 'Musculiv', 'Dorflex', 'Analgésico muscular', false, false, false, '{}', array['dor_muscular','trauma_membro'], '{}', array['musculiv','dorflex'], '1 dose', 'a cada 8 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 3, false),
  ('DORMAX', 'DorMax', 'Morfina', 'Analgésico controlado', true, false, true, '{}', array['dor_intensa','trauma_craniano','trauma_membro','dor_muscular'], '{}', array['dormax','morfina'], '10 mg', 'a cada 6 horas, se necessário', '1 dia', 1, 'Oral/hospitalar conforme regra RP', 'Uso controlado. Justificativa clínica obrigatória.', 4, true),
  ('GLICOVIDA', 'GlicoVida', 'Insulina', 'Metabólico', false, false, false, array['endocrino','metabolico'], array['diabetes','hiperglicemia'], '{}', array['glicovida','insulina'], '1 aplicação', '1x/dia', '3 dias', 3, 'Subcutânea', 'Uma aplicação corresponde a um item RP.', 1, false),
  ('ORGABLOQ', 'OrgaBloq', 'Orgalutran / Ganirelix', 'Fertilidade', false, false, false, array['reprodutivo','ginecologico','fertilidade'], array['fertilidade'], '{}', array['orgabloq','orgalutran','ganirelix'], '0,25 mg', '1x/dia', '5 dias', 5, 'Subcutânea', 'Uma aplicação corresponde a um item RP.', 1, false),
  ('FERTIPLUS', 'FertiPlus', 'Puregon / Follitropina beta', 'Fertilidade', false, false, false, array['reprodutivo','ginecologico','fertilidade'], array['fertilidade'], '{}', array['fertiplus','puregon','follitropina'], '150 UI', '1x/dia', '7 dias', 7, 'Subcutânea', 'Uma aplicação corresponde a um item RP.', 1, false),
  ('GESTAVIDA', 'GestaVida', 'Ogestan', 'Gestação', false, false, false, array['reprodutivo','obstetrico','gestacao'], array['gestacao','pre_natal'], '{}', array['gestavida','ogestan'], '1 dose', '1x/dia', '30 dias', 30, 'Oral', 'Seguir a frequência RP prescrita.', 1, false),
  ('CALCIFORT', 'CalciFort', 'Caltrate', 'Suplemento', false, false, false, '{}', '{}', '{}', array['calcifort','caltrate'], '1 dose', '1x/dia', '30 dias', 30, 'Oral', 'Seguir a frequência RP prescrita.', 1, false),
  ('MATERPLUS', 'MaterPlus', 'Materna', 'Suplemento', false, false, false, array['reprodutivo','obstetrico','gestacao'], array['gestacao','pre_natal'], '{}', array['materplus','materna'], '1 dose', '1x/dia', '30 dias', 30, 'Oral', 'Seguir a frequência RP prescrita.', 1, false),
  ('CALMIVITA', 'Calmivita', 'Rivotril / Clonazepam', 'Controlado', true, false, true, array['neurologico','psiquiatrico'], array['crise_ansiosa','convulsao'], '{}', array['calmivita','rivotril','clonazepam'], '0,5 mg', '1x/dia', '3 dias', 3, 'Oral', 'Uso controlado. Justificativa clínica obrigatória.', 1, false),
  ('ALERGICOR', 'Alergicor', 'Desloratadina', 'Antialérgico', false, false, false, '{}', array['reacao_alergica'], '{}', array['alergicor','desloratadina'], '5 mg', '1x/dia', '5 dias', 5, 'Oral', 'Seguir a frequência RP prescrita.', 1, false),
  ('ALERGIX', 'Alergix', 'Loratadina', 'Antialérgico', false, false, false, '{}', array['reacao_alergica'], '{}', array['alergix','loratadina'], '10 mg', '1x/dia', '5 dias', 5, 'Oral', 'Seguir a frequência RP prescrita.', 1, false),
  ('RESPIMAX', 'Respimax', 'Salbutamol', 'Respiratório', false, false, false, array['respiratorio'], array['dispneia','crise_respiratoria'], '{}', array['respimax','salbutamol'], '1 dose / administração RP', 'a cada 6 horas, se necessário', '5 dias', 5, 'Inalatória', 'Cada administração corresponde a um item RP.', 4, true),
  ('GRIPEX', 'Gripex', 'Benegrip', 'Sintomático', false, false, false, array['respiratorio','infeccioso'], array['gripe','resfriado'], '{}', array['gripex','benegrip'], '1 dose', 'a cada 8 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 3, false),
  ('BACTRIMED', 'Bactrimed', 'Azitromicina', 'Antibiótico', false, true, true, '{}', array['infeccao'], array['gripe_simples','resfriado','dor_isolada','mal_estar_inespecifico'], array['bactrimed','azitromicina'], '500 mg', '1x/dia', '3 dias', 3, 'Oral', 'Antibiótico RP. Justificativa clínica obrigatória.', 1, false),
  ('BACTERON', 'Bacteron', 'Amoxicilina', 'Antibiótico', false, true, true, '{}', array['infeccao'], array['gripe_simples','resfriado','dor_isolada','mal_estar_inespecifico'], array['bacteron','amoxicilina'], '500 mg', 'a cada 8 horas', '7 dias', 7, 'Oral', 'Antibiótico RP. Justificativa clínica obrigatória.', 3, false),
  ('INFLAMOL', 'Inflamol', 'Nimesulida', 'Anti-inflamatório', false, false, false, '{}', array['dor_muscular','trauma_membro','inflamacao'], '{}', array['inflamol','nimesulida'], '100 mg', 'a cada 12 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 2, false),
  ('INFLAMAX', 'Inflamax', 'Ibuprofeno', 'Anti-inflamatório', false, false, false, '{}', array['dor_muscular','trauma_membro','inflamacao'], '{}', array['inflamax','ibuprofeno'], '400 mg', 'a cada 8 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 3, false),
  ('GASTRIX', 'Gastrix', 'Omeprazol', 'Gastrointestinal', false, false, false, array['digestivo'], array['dor_abdominal','gastrite','refluxo'], '{}', array['gastrix','omeprazol'], '20 mg', '1x/dia', '7 dias', 7, 'Oral', 'Seguir a frequência RP prescrita.', 1, false),
  ('GASILIV', 'Gasiliv', 'Luftal / Simeticona', 'Gastrointestinal', false, false, false, array['digestivo'], array['gases','dor_abdominal','colica'], '{}', array['gasiliv','luftal','simeticona'], '40 mg', 'a cada 8 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 3, false),
  ('HEPAVIDA', 'Hepavida', 'Eparema', 'Gastrointestinal', false, false, false, array['digestivo'], array['indigestao','mal_estar_digestivo'], '{}', array['hepavida','eparema'], '1 dose', 'a cada 12 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 2, false),
  ('NAUSEAZERO', 'NáuseaZero', 'Dramin / Dimenidrinato', 'Antiemético', false, false, false, array['digestivo','neurologico'], array['nausea','vomitos'], '{}', array['nauseazero','náuseazero','dramin','dimenidrinato'], '50 mg', 'a cada 6 horas, se necessário', '3 dias', 3, 'Oral', 'Usar se necessário, respeitando a frequência máxima RP.', 4, true),
  ('COLICACALM', 'CólicaCalm', 'Buscopan', 'Antiespasmódico', false, false, false, array['digestivo','urinario','reprodutivo'], array['colica','dor_abdominal'], '{}', array['colicacalm','cólicacalm','buscopan'], '10 mg', 'a cada 8 horas', '3 dias', 3, 'Oral', 'Seguir a frequência RP prescrita.', 3, false),
  ('RESSAK', 'Ressak', 'Engov', 'Sintomático', false, false, false, array['digestivo'], array['nausea','mal_estar_digestivo'], '{}', array['ressak','engov'], '1 dose', 'a cada 8 horas, se necessário', '1 dia', 1, 'Oral', 'Usar se necessário, respeitando a frequência máxima RP.', 3, true);

insert into public.rp_medication_versions (medication_id, version, snapshot, change_reason)
select medication.id, medication.version, to_jsonb(medication) - 'created_at' - 'updated_at', 'SEED_INICIAL_ANJOS_PHARMA'
from public.rp_medications medication;

create or replace function private.rp_frequency_doses_per_day(p_frequency text)
returns integer
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_frequency text := lower(regexp_replace(btrim(coalesce(p_frequency, '')), '\s+', ' ', 'g'));
  v_interval integer;
  v_times integer;
begin
  if v_frequency = '' then raise exception 'Informe a frequência.'; end if;
  v_times := nullif((regexp_match(v_frequency, '(^|[^0-9])([1-9]|1[0-9]|2[0-4])\s*x\s*/?\s*dia'))[2], '')::integer;
  if v_times is not null then return v_times; end if;
  v_interval := nullif((regexp_match(v_frequency, '(^|[^0-9])(24|12|8|6|4)\s*/\s*\2\s*h'))[2], '')::integer;
  if v_interval is null then
    v_interval := nullif((regexp_match(v_frequency, 'a cada\s+(24|12|8|6|4)\s+hora'))[1], '')::integer;
  end if;
  if v_interval is null then raise exception 'Use uma frequência RP suportada: 1x/dia a 4x/dia ou intervalos de 24, 12, 8, 6 ou 4 horas.'; end if;
  return 24 / v_interval;
end;
$$;

create or replace function private.rp_quantity(p_frequency text, p_duration_days integer)
returns integer
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_quantity integer;
begin
  if p_duration_days not between 1 and 365 then raise exception 'A duração deve ficar entre 1 e 365 dias.'; end if;
  v_quantity := private.rp_frequency_doses_per_day(p_frequency) * p_duration_days;
  if v_quantity not between 1 and 1000 then raise exception 'A quantidade calculada está fora do limite RP.'; end if;
  return v_quantity;
end;
$$;

create or replace function private.rp_case_signature(p_consultation_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select generation.response_payload->'case_signature'
      from public.consultation_ai_generations generation
      where generation.consultation_id = p_consultation_id
        and generation.action_type = 'CLINICAL_SYNTHESIS'
        and generation.status = 'completed'
    ),
    (
      select generation.response_payload->'case_signature'
      from public.consultation_ai_generations generation
      where generation.consultation_id = p_consultation_id
        and generation.action_type = 'EXAM_SUGGESTIONS'
        and generation.status = 'completed'
    ),
    jsonb_build_object('body_system', 'geral', 'case_tags', '[]'::jsonb, 'vital_flags', '[]'::jsonb)
  );
$$;

create or replace function private.rp_medication_context_compatible(
  p_consultation_id bigint,
  p_medication_id text
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_medication public.rp_medications;
  v_consultation public.clinical_consultations;
  v_allergies text;
  v_signature jsonb;
  v_body_system text;
  v_tags text[];
begin
  select * into v_medication from public.rp_medications where id = p_medication_id and active;
  if v_medication.id is null then return false; end if;
  select * into v_consultation
  from public.clinical_consultations consultation
  where consultation.id = p_consultation_id;
  if v_consultation.id is null then return false; end if;
  select lower(coalesce(patient.allergies, '')) into v_allergies
  from public.patients patient where patient.id = v_consultation.patient_id;
  if exists (
    select 1 from unnest(v_medication.allergy_keywords) keyword
    where char_length(keyword) >= 3 and v_allergies like '%' || lower(keyword) || '%'
  ) then return false; end if;
  v_signature := private.rp_case_signature(p_consultation_id);
  v_body_system := lower(coalesce(v_signature->>'body_system', 'geral'));
  select coalesce(array_agg(lower(value)), '{}'::text[]) into v_tags
  from jsonb_array_elements_text(coalesce(v_signature->'case_tags', '[]'::jsonb)) value;
  if cardinality(v_medication.disallowed_case_tags) > 0
     and v_tags && v_medication.disallowed_case_tags then return false; end if;
  if v_medication.id = 'DORMAX'
     and coalesce(v_consultation.pain_score, 0) < 7
     and not (v_tags && v_medication.allowed_case_tags) then return false; end if;
  if cardinality(v_medication.allowed_body_systems) = 0
     and cardinality(v_medication.allowed_case_tags) = 0 then return true; end if;
  return v_body_system = any(v_medication.allowed_body_systems)
    or v_tags && v_medication.allowed_case_tags;
end;
$$;

create or replace function private.ensure_consultation_prescription(
  p_consultation_id bigint,
  p_actor uuid
)
returns public.consultation_prescriptions
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_prescription public.consultation_prescriptions;
  v_consultation public.clinical_consultations;
  v_passport text;
begin
  select * into v_consultation from public.clinical_consultations where id = p_consultation_id for update;
  if v_consultation.id is null then raise exception 'Consulta não localizada.'; end if;
  if v_consultation.status <> 'in_progress' then raise exception 'A prescrição concluída é imutável.'; end if;
  if not private.can_edit_consultation(p_actor, v_consultation.professional_id) then raise exception 'Acesso não autorizado.' using errcode = '42501'; end if;
  select * into v_prescription from public.consultation_prescriptions where consultation_id = p_consultation_id for update;
  if v_prescription.id is null then
    insert into public.consultation_prescriptions (consultation_id, professional_id)
    values (p_consultation_id, v_consultation.professional_id)
    returning * into v_prescription;
    select passport into v_passport from public.profiles where user_id = p_actor;
    insert into public.audit_logs (actor_user_id, actor_passport, action, entity_name, entity_id, new_values)
    values (p_actor, v_passport, 'PRESCRIPTION_CREATED', 'consultation_prescriptions', v_prescription.id::text,
      jsonb_build_object('consultation_id', p_consultation_id));
  end if;
  return v_prescription;
end;
$$;

create or replace function public.upsert_consultation_prescription_item(
  p_consultation_id bigint,
  p_item_id uuid,
  p_medication_id text,
  p_source text,
  p_reason text,
  p_dose text,
  p_frequency text,
  p_duration_days integer,
  p_route text,
  p_instructions text,
  p_justification text default null,
  p_final_quantity integer default null,
  p_override_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := private.hpsm_current_actor();
  v_passport text;
  v_prescription public.consultation_prescriptions;
  v_medication public.rp_medications;
  v_item public.consultation_prescription_items;
  v_old public.consultation_prescription_items;
  v_calculated integer;
  v_final integer;
  v_override boolean;
  v_is_suggestion boolean;
begin
  if p_source not in ('ai', 'manual') then raise exception 'Origem da medicação inválida.'; end if;
  select * into v_medication from public.rp_medications where id = upper(btrim(coalesce(p_medication_id, ''))) and active;
  if v_medication.id is null then raise exception 'Medicamento inexistente ou inativo.'; end if;
  if not private.rp_medication_context_compatible(p_consultation_id, v_medication.id) then
    raise exception 'O medicamento é incompatível com o contexto clínico ou com as alergias informadas.';
  end if;
  v_is_suggestion := exists (
    select 1
    from public.clinical_consultations consultation,
      jsonb_array_elements(coalesce(consultation.selected_diagnosis->'medication_suggestions', '[]'::jsonb)) suggestion
    where consultation.id = p_consultation_id and suggestion->>'medication_id' = v_medication.id
  );
  if p_source = 'ai' and not v_is_suggestion then raise exception 'A sugestão de medicamento não pertence ao diagnóstico selecionado.'; end if;
  if char_length(btrim(coalesce(p_reason, ''))) not between 3 and 1000 then raise exception 'Informe o motivo da prescrição.'; end if;
  if char_length(btrim(coalesce(p_dose, ''))) not between 1 and 80
     or char_length(btrim(coalesce(p_frequency, ''))) not between 1 and 120
     or char_length(btrim(coalesce(p_route, ''))) not between 1 and 120
     or char_length(btrim(coalesce(p_instructions, ''))) not between 1 and 500 then
    raise exception 'Revise dose, frequência, via e orientações.';
  end if;
  if v_medication.requires_justification and char_length(btrim(coalesce(p_justification, ''))) not between 3 and 1000 then
    raise exception 'Este medicamento exige justificativa clínica.';
  end if;
  v_calculated := private.rp_quantity(p_frequency, p_duration_days);
  v_final := coalesce(p_final_quantity, v_calculated);
  if v_final not between 1 and 1000 then raise exception 'A quantidade final está fora do limite RP.'; end if;
  v_override := v_final <> v_calculated;
  if v_override and char_length(btrim(coalesce(p_override_reason, ''))) not between 3 and 500 then
    raise exception 'Informe o motivo do ajuste manual da quantidade.';
  end if;
  v_prescription := private.ensure_consultation_prescription(p_consultation_id, v_actor);
  if p_item_id is not null then
    select * into v_old from public.consultation_prescription_items
    where id = p_item_id and prescription_id = v_prescription.id for update;
    if v_old.id is null then raise exception 'Item da prescrição não localizado.'; end if;
    if v_old.medication_id <> v_medication.id then raise exception 'O medicamento de um item existente não pode ser trocado.'; end if;
    update public.consultation_prescription_items set
      source = p_source,
      dose_snapshot = btrim(p_dose),
      frequency_snapshot = btrim(p_frequency),
      duration_snapshot = p_duration_days::text || case when p_duration_days = 1 then ' dia' else ' dias' end,
      duration_days = p_duration_days,
      route_snapshot = btrim(p_route),
      reason_snapshot = btrim(p_reason),
      instructions_snapshot = btrim(p_instructions),
      justification_snapshot = nullif(btrim(coalesce(p_justification, '')), ''),
      calculated_quantity_snapshot = v_calculated,
      final_quantity_snapshot = v_final,
      quantity_override_snapshot = v_override,
      override_reason = case when v_override then btrim(p_override_reason) else null end,
      updated_at = now()
    where id = v_old.id returning * into v_item;
  else
    insert into public.consultation_prescription_items (
      prescription_id, consultation_id, medication_id, source, catalog_version,
      rp_name_snapshot, reference_name_snapshot, dose_snapshot, frequency_snapshot,
      duration_snapshot, duration_days, route_snapshot, reason_snapshot,
      instructions_snapshot, justification_snapshot, calculated_quantity_snapshot,
      final_quantity_snapshot, quantity_override_snapshot, override_reason, professional_id
    ) values (
      v_prescription.id, p_consultation_id, v_medication.id, p_source, v_medication.version,
      v_medication.rp_name, v_medication.reference_name, btrim(p_dose), btrim(p_frequency),
      p_duration_days::text || case when p_duration_days = 1 then ' dia' else ' dias' end,
      p_duration_days, btrim(p_route), btrim(p_reason), btrim(p_instructions),
      nullif(btrim(coalesce(p_justification, '')), ''), v_calculated, v_final,
      v_override, case when v_override then btrim(p_override_reason) else null end,
      v_prescription.professional_id
    ) returning * into v_item;
  end if;
  insert into public.consultation_medication_decisions (
    consultation_id, medication_id, source, decision, reason, actor_user_id
  ) values (p_consultation_id, v_medication.id, p_source, 'accepted', btrim(p_reason), v_actor);
  select passport into v_passport from public.profiles where user_id = v_actor;
  insert into public.audit_logs (actor_user_id, actor_passport, action, entity_name, entity_id, old_values, new_values)
  values (
    v_actor, v_passport,
    case when p_item_id is null and p_source = 'manual' then 'MEDICATION_ADDED_MANUALLY'
         when p_item_id is null then 'MEDICATION_SUGGESTION_ACCEPTED'
         else 'PRESCRIPTION_ITEM_UPDATED' end,
    'consultation_prescription_items', v_item.id::text,
    case when v_old.id is null then null else to_jsonb(v_old) - 'professional_id' end,
    (to_jsonb(v_item) - 'professional_id') || jsonb_build_object('calculated_quantity', v_calculated, 'final_quantity', v_final)
  );
  if v_override then
    insert into public.audit_logs (actor_user_id, actor_passport, action, entity_name, entity_id, new_values)
    values (v_actor, v_passport, 'PRESCRIPTION_QUANTITY_OVERRIDDEN', 'consultation_prescription_items', v_item.id::text,
      jsonb_build_object('calculated_quantity', v_calculated, 'final_quantity', v_final, 'reason', btrim(p_override_reason)));
  end if;
  return to_jsonb(v_item) - 'professional_id';
exception when unique_violation then
  raise exception 'Este medicamento já integra a prescrição. Edite o item existente.';
end;
$$;

create or replace function public.reject_consultation_medication_suggestion(
  p_consultation_id bigint,
  p_medication_id text,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := private.hpsm_current_actor();
  v_prescription public.consultation_prescriptions;
  v_medication_id text := upper(btrim(coalesce(p_medication_id, '')));
  v_passport text;
begin
  if not exists (
    select 1
    from public.clinical_consultations consultation,
      jsonb_array_elements(coalesce(consultation.selected_diagnosis->'medication_suggestions', '[]'::jsonb)) suggestion
    where consultation.id = p_consultation_id and suggestion->>'medication_id' = v_medication_id
  ) then raise exception 'Sugestão de medicamento não localizada.'; end if;
  v_prescription := private.ensure_consultation_prescription(p_consultation_id, v_actor);
  delete from public.consultation_prescription_items where consultation_id = p_consultation_id and medication_id = v_medication_id;
  insert into public.consultation_medication_decisions (consultation_id, medication_id, source, decision, reason, actor_user_id)
  values (p_consultation_id, v_medication_id, 'ai', 'rejected', nullif(btrim(coalesce(p_reason, '')), ''), v_actor);
  select passport into v_passport from public.profiles where user_id = v_actor;
  insert into public.audit_logs (actor_user_id, actor_passport, action, entity_name, entity_id, new_values)
  values (v_actor, v_passport, 'MEDICATION_SUGGESTION_REJECTED', 'clinical_consultations', p_consultation_id::text,
    jsonb_build_object('medication_id', v_medication_id, 'reason', nullif(btrim(coalesce(p_reason, '')), '')));
end;
$$;

create or replace function public.remove_consultation_prescription_item(
  p_consultation_id bigint,
  p_item_id uuid,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := private.hpsm_current_actor();
  v_item public.consultation_prescription_items;
  v_prescription public.consultation_prescriptions;
  v_passport text;
begin
  v_prescription := private.ensure_consultation_prescription(p_consultation_id, v_actor);
  select * into v_item from public.consultation_prescription_items
  where id = p_item_id and prescription_id = v_prescription.id for update;
  if v_item.id is null then raise exception 'Item da prescrição não localizado.'; end if;
  delete from public.consultation_prescription_items where id = v_item.id;
  insert into public.consultation_medication_decisions (consultation_id, medication_id, source, decision, reason, actor_user_id)
  values (p_consultation_id, v_item.medication_id, v_item.source, 'removed', nullif(btrim(coalesce(p_reason, '')), ''), v_actor);
  select passport into v_passport from public.profiles where user_id = v_actor;
  insert into public.audit_logs (actor_user_id, actor_passport, action, entity_name, entity_id, old_values, new_values)
  values (v_actor, v_passport, 'PRESCRIPTION_ITEM_REMOVED', 'consultation_prescription_items', v_item.id::text,
    to_jsonb(v_item) - 'professional_id', jsonb_build_object('reason', nullif(btrim(coalesce(p_reason, '')), '')));
end;
$$;

create or replace function private.finalize_consultation_prescription(
  p_consultation_id bigint,
  p_finalized_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_prescription public.consultation_prescriptions;
  v_consultation public.clinical_consultations;
  v_patient public.patients;
  v_professional public.profiles;
  v_position public.staff_positions;
  v_identity public.professional_identities;
  v_snapshot jsonb;
  v_suggestions text[];
  v_reviewed text[];
begin
  select * into v_consultation from public.clinical_consultations where id = p_consultation_id for update;
  select coalesce(array_agg(distinct suggestion->>'medication_id'), '{}'::text[]) into v_suggestions
  from jsonb_array_elements(coalesce(v_consultation.selected_diagnosis->'medication_suggestions', '[]'::jsonb)) suggestion;
  select coalesce(array_agg(distinct decision.medication_id), '{}'::text[]) into v_reviewed
  from public.consultation_medication_decisions decision
  where decision.consultation_id = p_consultation_id;
  if not (v_suggestions <@ v_reviewed) then raise exception 'Revise cada sugestão de medicamento antes de concluir.'; end if;
  select * into v_prescription from public.consultation_prescriptions where consultation_id = p_consultation_id for update;
  if v_prescription.id is null then return null; end if;
  if v_prescription.status = 'finalized' then return v_prescription.final_snapshot; end if;
  if not exists (select 1 from public.consultation_prescription_items where prescription_id = v_prescription.id) then return null; end if;
  select * into v_patient from public.patients where id = v_consultation.patient_id;
  select * into v_professional from public.profiles where user_id = v_consultation.professional_id;
  select * into v_position from public.staff_positions where id = v_professional.position_id;
  select * into v_identity from public.professional_identities where user_id = v_professional.user_id and status = 'active';
  if v_identity.user_id is null or v_identity.crm_code !~ '^[0-9]{8}$' or v_identity.signature_image_path is null then
    raise exception 'A identidade profissional ainda está sendo preparada. Gere a assinatura e o CRM antes de concluir.';
  end if;
  update public.consultation_prescription_items set
    professional_name_snapshot = v_professional.display_name,
    crm_snapshot = v_identity.crm_code,
    role_snapshot = v_position.name,
    updated_at = now()
  where prescription_id = v_prescription.id;
  select jsonb_build_object(
    'schema', 'hpsm.rp_prescription.v1',
    'prescription_id', v_prescription.id,
    'consultation_id', p_consultation_id,
    'patient', jsonb_build_object('name', v_patient.name, 'passport', v_patient.passport),
    'professional', jsonb_build_object(
      'id', v_professional.user_id,
      'name', v_professional.display_name,
      'crm_code', v_identity.crm_code,
      'role', v_position.name,
      'signature_image_path', v_identity.signature_image_path
    ),
    'created_at', v_prescription.created_at,
    'finalized_at', p_finalized_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', item.id,
        'medication_id', item.medication_id,
        'rp_name_snapshot', item.rp_name_snapshot,
        'reference_name_snapshot', item.reference_name_snapshot,
        'dose_snapshot', item.dose_snapshot,
        'frequency_snapshot', item.frequency_snapshot,
        'duration_snapshot', item.duration_snapshot,
        'route_snapshot', item.route_snapshot,
        'reason_snapshot', item.reason_snapshot,
        'instructions_snapshot', item.instructions_snapshot,
        'justification_snapshot', item.justification_snapshot,
        'calculated_quantity_snapshot', item.calculated_quantity_snapshot,
        'final_quantity_snapshot', item.final_quantity_snapshot,
        'quantity_override_snapshot', item.quantity_override_snapshot,
        'override_reason', item.override_reason,
        'professional_id', item.professional_id,
        'professional_name_snapshot', item.professional_name_snapshot,
        'crm_snapshot', item.crm_snapshot,
        'role_snapshot', item.role_snapshot,
        'created_at', item.created_at
      ) order by item.created_at, item.id)
      from public.consultation_prescription_items item
      where item.prescription_id = v_prescription.id
    ), '[]'::jsonb),
    'rp_notice', 'As posologias, dosagens e orientações são regras fictícias e simplificadas, destinadas exclusivamente ao uso em RP.'
  ) into v_snapshot;
  update public.consultation_prescriptions set
    status = 'finalized', patient_name_snapshot = v_patient.name,
    patient_passport_snapshot = v_patient.passport,
    professional_name_snapshot = v_professional.display_name,
    crm_snapshot = v_identity.crm_code, role_snapshot = v_position.name,
    final_snapshot = v_snapshot, finalized_at = p_finalized_at, updated_at = now()
  where id = v_prescription.id;
  insert into public.audit_logs (actor_user_id, actor_passport, action, entity_name, entity_id, new_values)
  values (v_professional.user_id, v_professional.passport, 'PRESCRIPTION_FINALIZED', 'consultation_prescriptions', v_prescription.id::text,
    jsonb_build_object('consultation_id', p_consultation_id, 'item_count', jsonb_array_length(v_snapshot->'items')));
  return v_snapshot;
end;
$$;

comment on table public.rp_medications is
  'Catálogo canônico Anjos Pharma. Não representa estoque, saldo, entrada, saída ou movimentação.';
comment on table public.clinical_protocols is
  'Protocolos clínicos autoalimentados exclusivamente por consultas concluídas, sem dados pessoais em seu conteúdo.';
comment on table public.clinical_protocol_observations is
  'Uma evidência desidentificada por consulta concluída; a unicidade impede autoreforço.';
comment on table public.consultation_prescription_items is
  'Snapshot editável durante a consulta e imutável após a conclusão; quantidade RP não representa estoque.';
