-- Benefícios por atendimento e ciclo seguro de ativação/renovação do plano HPSM.

insert into public.system_permissions (code, module, label, description, sort_order)
values (
  'healthplans.review',
  'Atendimento',
  'Analisar ativações do plano de saúde',
  'Confirma pagamentos, ativa, renova ou recusa solicitações do Plano de Saúde HPSM.',
  105
)
on conflict (code) do update
set module = excluded.module,
    label = excluded.label,
    description = excluded.description,
    sort_order = excluded.sort_order;

with actor as (
  select user_id
  from public.profiles
  where role_code = 'diretor_geral'
  limit 1
)
insert into public.staff_position_permissions (position_id, permission_code, granted_by)
select position.id, 'healthplans.review', actor.user_id
from public.staff_positions as position
cross join actor
where position.level between 11 and 14
on conflict (position_id, permission_code) do nothing;

create table public.patient_health_plan_requests (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on update restrict on delete restrict,
  attendance_id bigint not null unique references public.attendances(id) on update restrict on delete restrict,
  status text not null default 'pending'
    constraint patient_health_plan_requests_status_check
    check (status in ('pending', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(user_id) on update restrict on delete set null,
  reviewed_at timestamptz,
  rejection_reason text,
  coverage_start timestamptz,
  coverage_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint patient_health_plan_requests_resolution_check check (
    (
      status = 'pending'
      and reviewed_by is null
      and reviewed_at is null
      and rejection_reason is null
      and coverage_start is null
      and coverage_end is null
    )
    or
    (
      status = 'approved'
      and reviewed_by is not null
      and reviewed_at is not null
      and rejection_reason is null
      and coverage_start is not null
      and coverage_end is not null
      and coverage_end > coverage_start
    )
    or
    (
      status = 'rejected'
      and reviewed_by is not null
      and reviewed_at is not null
      and char_length(btrim(rejection_reason)) between 10 and 2000
      and coverage_start is null
      and coverage_end is null
    )
  )
);

create index patient_health_plan_requests_pending_idx
  on public.patient_health_plan_requests (requested_at, id)
  where status = 'pending';

create index patient_health_plan_requests_patient_approved_idx
  on public.patient_health_plan_requests (patient_id, coverage_end desc)
  where status = 'approved';

create index patient_health_plan_requests_reviewed_by_idx
  on public.patient_health_plan_requests (reviewed_by)
  where reviewed_by is not null;

create trigger patient_health_plan_requests_touch_updated_at
before update on public.patient_health_plan_requests
for each row execute function private.touch_updated_at();

create trigger patient_health_plan_requests_audit
after insert or update on public.patient_health_plan_requests
for each row execute function private.audit_row_change();

alter table public.patient_health_plan_requests enable row level security;
alter table public.patient_health_plan_requests force row level security;

create policy patient_health_plan_requests_read_reviewers
on public.patient_health_plan_requests
for select to authenticated
using (private.has_permission((select auth.uid()), 'healthplans.review'));

revoke all on public.patient_health_plan_requests from public, anon, authenticated, service_role;
revoke all on sequence public.patient_health_plan_requests_id_seq from public, anon, authenticated, service_role;
grant select on public.patient_health_plan_requests to authenticated;
grant select, insert, update, delete on public.patient_health_plan_requests to service_role;
grant usage, select on sequence public.patient_health_plan_requests_id_seq to service_role;

create or replace function private.create_health_plan_request_from_sale()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_patient_id bigint;
  v_service_code text;
begin
  select catalog.code
  into v_service_code
  from public.service_catalog as catalog
  where catalog.id = new.service_id;

  if v_service_code is distinct from 'plano_saude_convenio' then
    return new;
  end if;

  if new.quantity <> 1 then
    raise exception 'O plano de saúde pode aparecer somente uma vez no atendimento.';
  end if;

  select attendance.patient_id
  into v_patient_id
  from public.attendances as attendance
  where attendance.id = new.attendance_id
    and attendance.status = 'completed';

  if not found then
    raise exception 'Atendimento do plano não localizado.';
  end if;

  insert into public.patient_health_plan_requests (patient_id, attendance_id)
  values (v_patient_id, new.attendance_id)
  on conflict (attendance_id) do nothing;

  return new;
end;
$$;

revoke all on function private.create_health_plan_request_from_sale() from public, anon, authenticated, service_role;

create trigger attendance_items_create_health_plan_request
after insert on public.attendance_items
for each row execute function private.create_health_plan_request_from_sale();

create or replace function private.notify_health_plan_workflow()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_seller_id uuid;
begin
  if tg_op = 'INSERT' and new.status = 'pending' then
    select attendance.performed_by
    into v_seller_id
    from public.attendances as attendance
    where attendance.id = new.attendance_id;

    insert into public.notifications (
      kind, audience, priority, title, body, action_url, created_by,
      source_type, source_id, required_permission
    ) values (
      'system', 'directors', 'important', 'Plano de saúde aguardando confirmação',
      'Uma venda do Plano de Saúde HPSM aguarda conferência do pagamento e decisão de ativação.',
      '/rh?aba=pendencias#planos-saude', v_seller_id,
      'health_plan_request', new.id::text, 'healthplans.review'
    );
  elsif tg_op = 'UPDATE' and old.status = 'pending' and new.status in ('approved', 'rejected') then
    perform private.resolve_flow_notifications('health_plan_request', new.id::text, new.reviewed_by);
  end if;

  return new;
end;
$$;

revoke all on function private.notify_health_plan_workflow() from public, anon, authenticated, service_role;

create trigger notifications_health_plan_workflow
after insert or update on public.patient_health_plan_requests
for each row execute function private.notify_health_plan_workflow();

create or replace function private.close_health_plan_request_on_attendance_cancel()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status = 'completed' and new.status = 'cancelled' then
    update public.patient_health_plan_requests
    set status = 'rejected',
        reviewed_by = new.cancelled_by,
        reviewed_at = coalesce(new.cancelled_at, now()),
        rejection_reason = 'Atendimento de origem cancelado antes da confirmação do plano.'
    where attendance_id = new.id
      and status = 'pending';
  end if;
  return new;
end;
$$;

revoke all on function private.close_health_plan_request_on_attendance_cancel() from public, anon, authenticated, service_role;

create trigger attendance_cancel_closes_health_plan_request
after update of status on public.attendances
for each row execute function private.close_health_plan_request_on_attendance_cancel();

create or replace function public.get_patient_health_plan_states(p_patient_ids bigint[])
returns table (
  patient_id bigint,
  status text,
  activated_at timestamptz,
  valid_until timestamptz,
  authorized_by uuid,
  authorized_by_name text,
  pending_request_id bigint,
  pending_requested_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null
     or not private.has_permission((select auth.uid()), 'patients.view') then
    raise exception 'Você não possui permissão para consultar pacientes.';
  end if;

  if p_patient_ids is null or cardinality(p_patient_ids) = 0 then
    return;
  end if;

  return query
  select
    patient.id,
    case
      when approved.id is not null and approved.coverage_end > now() then 'active'
      when approved.id is not null then 'expired'
      when pending.id is not null then 'awaiting_confirmation'
      else 'none'
    end,
    approved.coverage_start,
    approved.coverage_end,
    approved.reviewed_by,
    reviewer.display_name,
    pending.id,
    pending.requested_at
  from public.patients as patient
  left join lateral (
    select request.id, request.coverage_start, request.coverage_end, request.reviewed_by
    from public.patient_health_plan_requests as request
    where request.patient_id = patient.id
      and request.status = 'approved'
    order by request.coverage_end desc, request.id desc
    limit 1
  ) as approved on true
  left join public.profiles as reviewer on reviewer.user_id = approved.reviewed_by
  left join lateral (
    select request.id, request.requested_at
    from public.patient_health_plan_requests as request
    where request.patient_id = patient.id
      and request.status = 'pending'
    order by request.requested_at asc, request.id asc
    limit 1
  ) as pending on true
  where patient.id = any(p_patient_ids);
end;
$$;

revoke all on function public.get_patient_health_plan_states(bigint[]) from public, anon, authenticated, service_role;
grant execute on function public.get_patient_health_plan_states(bigint[]) to authenticated;
grant execute on function public.get_patient_health_plan_states(bigint[]) to service_role;

create or replace function public.review_patient_health_plan_request(
  p_request_id bigint,
  p_decision text,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := (select auth.uid());
  v_current_end timestamptz;
  v_decided_at timestamptz := now();
  v_request public.patient_health_plan_requests%rowtype;
  v_start timestamptz;
begin
  if v_actor_id is null or not private.has_permission(v_actor_id, 'healthplans.review') then
    raise exception 'Você não possui permissão para analisar planos de saúde.';
  end if;

  if p_decision not in ('approved', 'rejected') then
    raise exception 'Decisão inválida.';
  end if;

  select request.*
  into v_request
  from public.patient_health_plan_requests as request
  where request.id = p_request_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Solicitação não localizada.';
  end if;

  if v_request.status <> 'pending' then
    if v_request.status = p_decision then
      return jsonb_build_object(
        'id', v_request.id,
        'status', v_request.status,
        'valid_until', v_request.coverage_end,
        'already_reviewed', true
      );
    end if;
    raise exception using errcode = 'P0001', message = 'A solicitação já possui uma decisão diferente.';
  end if;

  perform 1
  from public.patients as patient
  where patient.id = v_request.patient_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Paciente não localizado.';
  end if;

  if p_decision = 'approved' then
    select max(request.coverage_end)
    into v_current_end
    from public.patient_health_plan_requests as request
    where request.patient_id = v_request.patient_id
      and request.status = 'approved';

    v_start := greatest(v_decided_at, coalesce(v_current_end, v_decided_at));

    update public.patient_health_plan_requests
    set status = 'approved',
        reviewed_by = v_actor_id,
        reviewed_at = v_decided_at,
        rejection_reason = null,
        coverage_start = v_start,
        coverage_end = v_start + interval '30 days'
    where id = v_request.id
    returning * into v_request;
  else
    if char_length(btrim(coalesce(p_reason, ''))) < 10 then
      raise exception 'Informe o motivo da recusa com pelo menos 10 caracteres.';
    end if;
    if char_length(btrim(p_reason)) > 2000 then
      raise exception 'O motivo da recusa deve ter no máximo 2000 caracteres.';
    end if;

    update public.patient_health_plan_requests
    set status = 'rejected',
        reviewed_by = v_actor_id,
        reviewed_at = v_decided_at,
        rejection_reason = btrim(p_reason),
        coverage_start = null,
        coverage_end = null
    where id = v_request.id
    returning * into v_request;
  end if;

  return jsonb_build_object(
    'id', v_request.id,
    'status', v_request.status,
    'valid_until', v_request.coverage_end,
    'already_reviewed', false
  );
end;
$$;

revoke all on function public.review_patient_health_plan_request(bigint, text, text) from public, anon, authenticated, service_role;
grant execute on function public.review_patient_health_plan_request(bigint, text, text) to authenticated;
grant execute on function public.review_patient_health_plan_request(bigint, text, text) to service_role;

-- O vínculo legado deixa de controlar descontos. Benefícios passam a pertencer
-- ao atendimento; a cobertura HPSM é derivada do histórico aprovado acima.
create or replace function private.guard_patient_plan_changes()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if (tg_op = 'INSERT' and new.plan_code is not null)
     or (tg_op = 'UPDATE' and new.plan_code is distinct from old.plan_code) then
    raise exception 'O benefício deve ser escolhido no atendimento; o Plano HPSM é ativado pela conferência de pagamento.';
  end if;
  return new;
end;
$$;

drop function public.create_attendance(bigint, jsonb, text);

create function public.create_attendance(
  p_patient_id bigint,
  p_items jsonb,
  p_notes text default null,
  p_benefit_code text default null
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_attendance_id bigint;
  v_discount numeric(18, 2);
  v_input_count integer;
  v_patient_name text;
  v_patient_passport text;
  v_plan_code text;
  v_plan_name text;
  v_subtotal numeric(18, 2);
  v_valid_count integer;
begin
  if not private.has_permission((select auth.uid()), 'attendances.create') then
    raise exception 'Você não possui permissão para registrar atendimentos.';
  end if;

  select patient.name, patient.passport
  into v_patient_name, v_patient_passport
  from public.patients as patient
  where patient.id = p_patient_id;

  if not found then
    raise exception 'Paciente não localizado.';
  end if;

  v_plan_code := nullif(btrim(coalesce(p_benefit_code, '')), '');
  if v_plan_code is not null then
    select plan.name
    into v_plan_name
    from public.benefit_plans as plan
    where plan.code = v_plan_code;
    if not found then
      raise exception 'Benefício inválido ou indisponível.';
    end if;
  end if;

  if p_notes is not null and char_length(p_notes) > 1000 then
    raise exception 'Observação muito longa.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Inclua ao menos um procedimento.';
  end if;

  v_input_count := jsonb_array_length(p_items);
  if v_input_count < 1 or v_input_count > 50 then
    raise exception 'Quantidade de procedimentos inválida.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as item(service_id bigint, quantity integer)
    group by service_id
    having count(*) <> 1
  ) then
    raise exception 'Cada item deve aparecer apenas uma vez.';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as item(service_id bigint, quantity integer)
    join public.service_catalog as catalog on catalog.id = item.service_id
    where catalog.code = 'plano_saude_convenio'
      and item.quantity <> 1
  ) then
    raise exception 'O plano de saúde pode aparecer somente uma vez no atendimento.';
  end if;

  with input_items as (
    select service_id, quantity
    from jsonb_to_recordset(p_items) as item(service_id bigint, quantity integer)
  )
  select
    count(*),
    coalesce(sum(catalog.unit_price * input_items.quantity), 0),
    coalesce(sum(round(catalog.unit_price * input_items.quantity * coalesce(discount.discount_percent, 0) / 100, 2)), 0)
  into v_valid_count, v_subtotal, v_discount
  from input_items
  join public.service_catalog as catalog
    on catalog.id = input_items.service_id
   and catalog.active = true
  left join public.plan_discounts as discount
    on discount.service_id = catalog.id
   and discount.plan_code = v_plan_code
  where input_items.quantity between 1 and 99;

  if v_valid_count <> v_input_count then
    raise exception 'Um dos itens não está disponível.';
  end if;

  insert into public.attendances (
    patient_id, patient_name, patient_passport, plan_code, plan_name,
    subtotal, discount, notes, performed_by
  ) values (
    p_patient_id, v_patient_name, v_patient_passport, v_plan_code, v_plan_name,
    v_subtotal, v_discount, nullif(btrim(coalesce(p_notes, '')), ''), (select auth.uid())
  )
  returning id into v_attendance_id;

  insert into public.attendance_items (
    attendance_id, service_id, service_name, unit_price, quantity, discount_percent
  )
  select
    v_attendance_id, catalog.id, catalog.name, catalog.unit_price,
    input_items.quantity::smallint, coalesce(discount.discount_percent, 0)
  from jsonb_to_recordset(p_items) as input_items(service_id bigint, quantity integer)
  join public.service_catalog as catalog
    on catalog.id = input_items.service_id
   and catalog.active = true
  left join public.plan_discounts as discount
    on discount.service_id = catalog.id
   and discount.plan_code = v_plan_code;

  return v_attendance_id;
end;
$$;

revoke all on function public.create_attendance(bigint, jsonb, text, text) from public, anon, authenticated, service_role;
grant execute on function public.create_attendance(bigint, jsonb, text, text) to authenticated;
grant execute on function public.create_attendance(bigint, jsonb, text, text) to service_role;

comment on table public.patient_health_plan_requests is
  'Solicitações idempotentes de ativação ou renovação do Plano de Saúde HPSM originadas por vendas concluídas.';
comment on function public.get_patient_health_plan_states(bigint[]) is
  'Retorna apenas o estado mínimo da cobertura necessário ao cadastro e ao atendimento, sem expor a fila administrativa.';
comment on function public.review_patient_health_plan_request(bigint, text, text) is
  'Confirma ou recusa uma solicitação com bloqueios para impedir dupla aprovação e perda de dias em renovações concorrentes.';
